name: "CI"

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Checks
      uses: pre-commit/action@v3.0.0

  gcc:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        cxx: [g++-14, g++-13, g++-12, g++-11]
    name: ${{ matrix.cxx }}
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v4
    - name: CMake
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update -y
        sudo apt-get install g++-11 g++-12 g++-13 g++-14
        cmake -B build
    - name: Build
      run: make -C build -j `nproc`
    - name: Test
      run: ./build/test/gtest/spblas-tests

  intel-llvm:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        mkl: [OFF, ON]
    name: intel-llvm${{ matrix.mkl == 'ON' && '-mkl' || '' }}
    env:
      CXX: icpx
    steps:
    - uses: actions/checkout@v4
    - name: Set up Intel
      run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
          | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update -y
          sudo apt-get install -y intel-oneapi-compiler-dpcpp-cpp intel-oneapi-mkl-devel
    - name: CMake
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake -B build -DENABLE_ONEMKL_SYCL=${{ matrix.mkl }}
    - name: Build
      run: |
        source /opt/intel/oneapi/setvars.sh
        make -C build -j `nproc`
    - name: Test
      run: |
        source /opt/intel/oneapi/setvars.sh
        ./build/test/gtest/spblas-tests

  armpl:
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Set up ArmPL
      run: |
        brew install --cask arm-performance-libraries
        ARMPL_PATH=$(echo /opt/arm/armpl*)
        echo "ARMPL_DIR=$ARMPL_PATH" >> $GITHUB_ENV
    - name: CMake
      run: |
        cmake -B build -DENABLE_ARMPL=ON
    - name: Build
      run: |
        make -C build -j
    - name: Test
      run: |
        ./build/test/gtest/spblas-tests
