name: "CI"

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Checks
      uses: pre-commit/action@v3.0.0

  gcc:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        cxx: [g++-13, g++-12, g++-11]
    name: ${{ matrix.cxx }}
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v4
    - name: CMake
      run: cmake -B build
    - name: Build
      run: make -C build -j `nproc`
    - name: Test
      run: ./build/test/gtest/spblas-tests

  icpx:
    runs-on: 'intel-ubuntu-latest'
    name: oneMKL
    env:
      CXX: icpx
    steps:
    - uses: actions/checkout@v4
    - name: CMake
      run: cmake -B build -DENABLE_ONEMKL=ON
    - name: Build
      run: make -C build -j `nproc`
    - name: Test
      run: ./build/test/gtest/spblas-tests
